### ISSUE TITLE
GMMReg

### ISSUE THREAD

**Issue by bing-jian** [huihut/CloudCompare-Qt#2]
Hi huihut,

This is Bing Jian,  the author of GMMReg package.  Thank you for including GMMReg to CloudCompare-Qt.  Just let you know that there is an updated version of GMMReg C++ implementation at
https://github.com/bing-jian/gmmreg
The latest version now supports 1) fast computation of Gauss transform using K-D tree
2) OpenMP 3) compiler level optimization and therefore should be much faster than the old version.

Thanks,  谢谢！
Bing

**Comment by huihut** [comment]
Hi Bing,
Thank you for your GMMReg, but this repo is not ready for maintenance.
